#!/usr/bin/env bash
# Generate firmware/main/secrets.h from secrets/tesla_secrets.env.
# secrets.h is git-ignored. Re-run whenever the .env changes.
set -euo pipefail

HERE="$(cd "$(dirname "$0")" && pwd)"
ENV_FILE="$HERE/../secrets/tesla_secrets.env"
OUT="$HERE/main/secrets.h"

[ -f "$ENV_FILE" ] || { echo "Missing $ENV_FILE — copy the example and fill it in."; exit 1; }

# shellcheck disable=SC1090
set -a; source "$ENV_FILE"; set +a

req() { [ -n "${!1:-}" ] || { echo "ERROR: $1 is empty in tesla_secrets.env"; exit 1; }; }
req WIFI_SSID; req WIFI_PASSWORD
req TESLA_CLIENT_ID; req TESLA_REFRESH_TOKEN; req TESLA_ENERGY_SITE_ID; req TESLA_AUDIENCE

cat > "$OUT" <<EOF
#pragma once
// AUTO-GENERATED by gen_secrets.sh — DO NOT COMMIT. (no client secret needed here)
#define WIFI_SSID            "${WIFI_SSID}"
#define WIFI_PASSWORD        "${WIFI_PASSWORD}"
#define TESLA_CLIENT_ID      "${TESLA_CLIENT_ID}"
#define TESLA_REFRESH_TOKEN  "${TESLA_REFRESH_TOKEN}"
#define TESLA_ENERGY_SITE_ID "${TESLA_ENERGY_SITE_ID}"
#define TESLA_AUDIENCE       "${TESLA_AUDIENCE}"
EOF

echo "Wrote $OUT"
